### ISSUE TITLE
Multiple .Net clients exists already

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-client-core#1]
I was just made aware of that it exists yet another .Net implementation of the `unleash-client`.  It would be nice if we could merge the best from both in to an official .Net client for Unleash. 

The clients:
- https://github.com/stiano/unleash-client-dotnet
- https://github.com/onybo/unleash-client-core

What do you say @onybo and @stiano, are you willing to collaborate on this? My .Net knowledge is rather limited and I would need you guys to take lead on this!

**Comment by stiano** [comment]
Sure, it would be good to consolidate our efforts into a single official client.

**Comment by onybo** [comment]
I agree.
I just now quickly scanned some of Stians code,  and I note that we would
have to agree on a common code style. I try to follow the code standard
used for the dotnet core project, and this would be my preference.

https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md

Best regards,
Olav Nybø

**Comment by onybo** [comment]
Relying on proprietary tools to provide readability is in my opinion not a good idea. Many developers prefers to not use Visual studio nor R#. Myself included.
Browsing code on github provides no special coloring of members.
And without really having done the work to back it by solid numbers, to me it seems that the coding guidelines used by the .Net core team and the MVC team, prefixing included, is most commonly used. 
At least big libraries that I have checked, such as .Net core, MVC, EF Core, AutoMapper, AutoFac, StructureMap and IdentityServer use underscore to prefix members.
  
I can write and provide an editorconfig file (http://editorconfig.org/) which is supported by most editors, Visual studio included.

**Comment by stiano** [comment]
An editorconfig file is just fine.
