### ISSUE TITLE
Default strategies not available when supplying custom strategies

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-client-core#10]
I would have expected the custom strategies to be added to the default ones. Unfortunately the default ones are skipped.

If this is a deliberate design decision, please consider exposing a public property to access the default strategies, so one can choose to pass these in as part of the custom strategies.

**Comment by Excolo** [comment]
I'd like to work on this. 
Do you have a preferred way to go about this? There are several different options as I see it. I was considering making this the default behavior, and then provide an overload with a bool to indicate that it should override the default strategies. Making this the default behavior, is a breaking change though.

**Comment by Excolo** [comment]
I've created a PR with my take on this issue. The breaking changes might make this solution unacceptable, so if that's the case, please let me know.

**Comment by silviogreuel** [comment]
I think that focusing on standards defined on unleash should have a higher priority. I'm still reading the docs and some existing code, all to understand what should be done... I'm quite busy on weekdays, and trying my best on weekends...

Maybe a branch 2.0.0 should be already going with breaking changes (like, lock in in .net-core, and some interface definitions)

**Comment by Excolo** [comment]
That sounds perfectly reasonable. I'll have a look at the official client libraries and apply any behavior regarding default strategies accordingly.
