### ISSUE TITLE
Reload WinForms project from sample folder

### ISSUE THREAD

**Issue by silviogreuel** [Unleash/unleash-client-core#31]
Reload and make the sample project compile again

**Comment by flerka** [comment]
Hi @silviogreuel ! Is it still relevant? Can't reproduce this issue on master branch. WinForms sample project compiles without errors.

**Comment by silviogreuel** [comment]
Yep, just reload and check for missing folders/imports, and check for AppVeyor build `.\build.ps1 -Target "AppVeyor"`

**Comment by flerka** [comment]
Sorry can't help, tried to reproduce it with build script you mentioned but there were no errors.

**Comment by silviogreuel** [comment]
Let me close this then, thanks @flerka
