### ISSUE TITLE
As a user, I would like to be able to fetch feature toggles synchronously during startup

### ISSUE THREAD

**Issue by mortenmj** [Unleash/unleash-client-core#50]
The Java client for Unleash (https://github.com/Unleash/unleash-client-java) has a flag in UnleashSettings called synchronousFetchOnInitialisation.
Currently, even though feature toggles can be fetched on startup (and are by default), it is not done synchronously.

Expected behavior is to have feature flags loaded immediately after instantiating DefaultUnleash. Observed behavior is that feature flags are loaded in the background, and available some time later. As far as I can tell, use of feature flags on startup requires a short sleep after calling DefaultUnleash, which is unpleasant and racecondition-y.

**Comment by AndreasChristianson** [comment]
I love this feature. I'll dig into what accomplishing this will take later this week.

**Comment by AndreasChristianson** [comment]
For those interested, this is a terribly kludgy workaround that might work for now:
```vb.net
Imports System.Runtime.CompilerServices
Imports System.Threading
Imports Unleash

Module UnleashExtensions

    <Extension()>
    Public Sub Ready(ByVal unleash As IUnleash)
        Dim stopWatch As New Diagnostics.Stopwatch()
        Dim timeout = 30
        stopWatch.Start()
        Do While Not CheckReady(unleash)
            Thread.Sleep(3000)
            If (stopWatch.Elapsed > TimeSpan.FromSeconds(timeout)) Then
                stopWatch.Stop()
                Throw New Exception("Unable to initialize unleash.")
            End If
        Loop
        stopWatch.Stop()
    End Sub

    Private Function CheckReady(unleash As IUnleash) As Boolean
        Return unleash.IsEnabled("well-known-always-on-feature-toggle", False)
    End Function
End Module
```
