### ISSUE TITLE
Add override option for providing context when checking a feature toggle

### ISSUE THREAD

**Issue by andywgarcia** [Unleash/unleash-client-core#54]
**Is your feature request related to a problem? Please describe.**
The programming pattern of using the global HttpContext is not a recommended pattern, nor is it natively supported by dotnet core.

A simple way to bypass this issue would be to pass in context with every request to check if a flag is enabled, but this is not available.

**Describe the solution you'd like**
Adding a simple override for passing in the context on `IsEnabled`

```
public bool IsEnabled(string toggleName, UnleashContext context, bool defaultSetting)
        {
            return CheckIsEnabled(toggleName, context, defaultSetting);
        }
```

**Describe alternatives you've considered**
1. Force the HttpContext to be available, but it goes against the reason why it was removed in the first place
https://stackoverflow.com/questions/38571032/how-to-get-httpcontext-current-in-asp-net-core
2. Make the `CheckIsEnabled` function public. This would work, but it is a naming inconsistency with the `IsEnabled`

**Additional context**
I will have authentication information in my controller of the request, but I currently can't access the HttpContext without some workaround. I was trying to figure out exactly what my ContextProvider will look like and since we don't have things like local cache or session information, but we have the userid at the time of the request, this seems like the best way that I can think of. 

If there is a better way to do this with a dotnetcore2.0 application, I would love to know.

**Comment by gnab** [comment]
Great input, @andywgarcia . Please have a look at the referenced commit and confirm that it solves your issue.

**Comment by andywgarcia** [comment]
@gnab Yup this solves my problem and exactly what I would have done in a fork. Thank you very much!

**Comment by andywgarcia** [comment]
@gnab Looking a bit more at the documentation in the readme, I am sure that could use an update as well for the section about using the context provider

**Comment by gnab** [comment]
@andywgarcia Indeed. The README needs to be revised, but we'll deal with that separately. The changes have been merged now and will be included in the next release.

**Comment by andywgarcia** [comment]
Thanks for the quick turnaround. Is there an ETA on the next release?

**Comment by andywgarcia** [comment]
@gnab Should there be an additional method as well with the default flag set to false so the option of `IsEnabled(string toggleName, UnleashContext context)` is available as well?

**Comment by gnab** [comment]
This has now been released in the new Unleash.Client 1.4.0 NuGet package.
