### ISSUE TITLE
API url not compliant

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-client-core#8]
It would be preferable to have this client accepting http://unleash.herokuapp.com/api/ as URL for Unleash to align with other Unleash clients.

**Comment by sebreynier** [comment]
Hi, do you know when it will be possible to get this new version from nuget? Do you plan to create a beta tag? It would fix my issue to get toggles from GitLab.

**Comment by silviogreuel** [comment]
I'll do some tests in production first, by friday or saturday should be released a new version. (actually this should be automated =X)

**Comment by sebreynier** [comment]
It seems perfect 😄 

Many thanks!

**Comment by sebreynier** [comment]
Hey @silviogreuel, do you know when the version 2.0.0 will be released?

**Comment by silviogreuel** [comment]
Released 1.3.6 @sebreynier

**Comment by sebreynier** [comment]
Yeah thanks 👍
